services:
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 9080:8080

  examplecrud:
    depends_on:
      - db
    image: examplecrud
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/example
