server:
  port: ${PORT:8080}
logging:
  level:
    org:
      atmosphere: warn
spring:
  sql:
    init:
      mode: always
  datasource:
    username: root
    password: example
    url: jdbc:mysql://localhost:3306/example
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  mustache:
    check-template-location: false
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
